import mock
import os
import pandas as pd
from datetime import datetime
from flexmock import flexmock
from sportsreference import utils
from sportsreference.constants import HOME
from sportsreference.ncaab.constants import BOXSCORES_URL, SCHEDULE_URL
from sportsreference.ncaab.boxscore import Boxscore, Boxscores


MONTH = 11
YEAR = 2017

BOXSCORE = '2017-11-24-21-purdue'


def read_file(filename):
    filepath = os.path.join(os.path.dirname(__file__), 'ncaab', filename)
    return open('%s' % filepath, 'r').read()


def mock_pyquery(url):
    class MockPQ:
        def __init__(self, html_contents):
            self.status_code = 200
            self.html_contents = html_contents
            self.text = html_contents

        def __call__(self, div):
            return read_file('table.html')

    if url == BOXSCORES_URL % (MONTH, 11, YEAR):
        return MockPQ(read_file('boxscores.html'))
    boxscore = read_file('%s.html' % BOXSCORE)
    return MockPQ(boxscore)


class MockDateTime:
    def __init__(self, year, month):
        self.year = year
        self.month = month


class TestNCAABBoxscore:
    @mock.patch('requests.get', side_effect=mock_pyquery)
    def setup_method(self, *args, **kwargs):
        self.results = {
            'date': 'November 24, 2017',
            'location': 'Imperial Arena at Atlantis Resort, Paradise Island',
            'winner': HOME,
            'winning_name': 'Purdue',
            'winning_abbr': 'PURDUE',
            'losing_name': 'Arizona',
            'losing_abbr': 'ARIZONA',
            'pace': 71.8,
            'away_ranking': 2,
            'away_win_percentage': .500,
            'away_wins': 3,
            'away_losses': 3,
            'away_minutes_played': 200,
            'away_field_goals': 25,
            'away_field_goal_attempts': 59,
            'away_field_goal_percentage': .424,
            'away_two_point_field_goals': 22,
            'away_two_point_field_goal_attempts': 42,
            'away_two_point_field_goal_percentage': .524,
            'away_three_point_field_goals': 3,
            'away_three_point_field_goal_attempts': 17,
            'away_three_point_field_goal_percentage': .176,
            'away_free_throws': 11,
            'away_free_throw_attempts': 16,
            'away_free_throw_percentage': .688,
            'away_offensive_rebounds': 6,
            'away_defensive_rebounds': 16,
            'away_total_rebounds': 22,
            'away_assists': 13,
            'away_steals': 4,
            'away_blocks': 3,
            'away_turnovers': 11,
            'away_personal_fouls': 20,
            'away_points': 64,
            'away_true_shooting_percentage': .480,
            'away_effective_field_goal_percentage': .449,
            'away_three_point_attempt_rate': .288,
            'away_free_throw_attempt_rate': .271,
            'away_offensive_rebound_percentage': 18.8,
            'away_defensive_rebound_percentage': 72.7,
            'away_total_rebound_percentage': 40.7,
            'away_assist_percentage': 52.0,
            'away_steal_percentage': 5.6,
            'away_block_percentage': 9.4,
            'away_turnover_percentage': 14.3,
            'away_offensive_rating': 88.9,
            'away_defensive_rating': 123.6,
            'home_ranking': 18,
            'home_win_percentage': .714,
            'home_wins': 5,
            'home_losses': 2,
            'home_minutes_played': 200,
            'home_field_goals': 31,
            'home_field_goal_attempts': 54,
            'home_field_goal_percentage': .574,
            'home_two_point_field_goals': 20,
            'home_two_point_field_goal_attempts': 32,
            'home_two_point_field_goal_percentage': .625,
            'home_three_point_field_goals': 11,
            'home_three_point_field_goal_attempts': 22,
            'home_three_point_field_goal_percentage': .500,
            'home_free_throws': 16,
            'home_free_throw_attempts': 21,
            'home_free_throw_percentage': .762,
            'home_offensive_rebounds': 6,
            'home_defensive_rebounds': 26,
            'home_total_rebounds': 32,
            'home_assists': 19,
            'home_steals': 6,
            'home_blocks': 7,
            'home_turnovers': 14,
            'home_personal_fouls': 19,
            'home_points': 89,
            'home_true_shooting_percentage': .696,
            'home_effective_field_goal_percentage': .676,
            'home_three_point_attempt_rate': .407,
            'home_free_throw_attempt_rate': .389,
            'home_offensive_rebound_percentage': 27.3,
            'home_defensive_rebound_percentage': 81.3,
            'home_total_rebound_percentage': 59.3,
            'home_assist_percentage': 61.3,
            'home_steal_percentage': 8.3,
            'home_block_percentage': 16.7,
            'home_turnover_percentage': 18.1,
            'home_offensive_rating': 123.6,
            'home_defensive_rating': 88.9
        }
        flexmock(utils) \
            .should_receive('_todays_date') \
            .and_return(MockDateTime(YEAR, MONTH))

        self.boxscore = Boxscore('2017-11-24-21-purdue')

    def test_ncaab_boxscore_returns_requested_boxscore(self):
        for attribute, value in self.results.items():
            assert getattr(self.boxscore, attribute) == value

    def test_invalid_url_yields_empty_class(self):
        flexmock(Boxscore) \
            .should_receive('_retrieve_html_page') \
            .and_return(None)

        boxscore = Boxscore(BOXSCORE)

        for key, value in boxscore.__dict__.items():
            if key == '_uri':
                continue
            assert value is None

    def test_ncaab_boxscore_dataframe_returns_dataframe_of_all_values(self):
        df = pd.DataFrame([self.results], index=[BOXSCORE])

        # Pandas doesn't natively allow comparisons of DataFrames.
        # Concatenating the two DataFrames (the one generated during the test
        # and the expected one above) and dropping duplicate rows leaves only
        # the rows that are unique between the two frames. This allows a quick
        # check of the DataFrame to see if it is empty - if so, all rows are
        # duplicates, and they are equal.
        frames = [df, self.boxscore.dataframe]
        df1 = pd.concat(frames).drop_duplicates(keep=False)

        assert df1.empty


class TestNCAABBoxscores:
    @mock.patch('requests.get', side_effect=mock_pyquery)
    def test_boxscores_search(self, *args, **kwargs):
        expected = {
            'boxscores': [
                {'boxscore': '2017-11-11-13-buffalo',
                 'away_name': 'Canisius',
                 'away_abbr': 'canisius',
                 'away_score': 75,
                 'away_rank': None,
                 'home_name': 'Buffalo',
                 'home_abbr': 'buffalo',
                 'home_score': 80,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-13-fairfield',
                 'away_name': 'Penn',
                 'away_abbr': 'pennsylvania',
                 'away_score': 72,
                 'away_rank': None,
                 'home_name': 'Fairfield',
                 'home_abbr': 'fairfield',
                 'home_score': 80,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-13-florida-gulf-coast',
                 'away_name': 'Illinois State',
                 'away_abbr': 'illinois-state',
                 'away_score': 87,
                 'away_rank': None,
                 'home_name': 'Florida Gulf Coast',
                 'home_abbr': 'florida-gulf-coast',
                 'home_score': 98,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-14-bradley',
                 'away_name': 'IUPUI',
                 'away_abbr': 'iupui',
                 'away_score': 53,
                 'away_rank': None,
                 'home_name': 'Bradley',
                 'home_abbr': 'bradley',
                 'home_score': 68,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-14-ohio',
                 'away_name': 'Alabama A&M',
                 'away_abbr': 'alabama-am',
                 'away_score': 53,
                 'away_rank': None,
                 'home_name': 'Ohio',
                 'home_abbr': 'ohio',
                 'home_score': 61,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-14-quinnipiac',
                 'away_name': 'Dartmouth',
                 'away_abbr': 'dartmouth',
                 'away_score': 77,
                 'away_rank': None,
                 'home_name': 'Quinnipiac',
                 'home_abbr': 'quinnipiac',
                 'home_score': 78,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-14-western-michigan',
                 'away_name': 'Siena Heights',
                 'away_abbr': 'Siena Heights',
                 'away_score': 72,
                 'away_rank': None,
                 'home_name': 'Western Michigan',
                 'home_abbr': 'western-michigan',
                 'home_score': 103,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-15-appalachian-state',
                 'away_name': 'Toccoa Falls',
                 'away_abbr': 'Toccoa Falls',
                 'away_score': 34,
                 'away_rank': None,
                 'home_name': 'Appalachian State',
                 'home_abbr': 'appalachian-state',
                 'home_score': 135,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-15-brown',
                 'away_name': 'Johnson & Wales (RI)',
                 'away_abbr': 'Johnson & Wales (RI)',
                 'away_score': 78,
                 'away_rank': None,
                 'home_name': 'Brown',
                 'home_abbr': 'brown',
                 'home_score': 106,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-15-drake',
                 'away_name': 'Coe',
                 'away_abbr': 'Coe',
                 'away_score': 54,
                 'away_rank': None,
                 'home_name': 'Drake',
                 'home_abbr': 'drake',
                 'home_score': 101,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-15-la-salle',
                 'away_name': "St. Peter's",
                 'away_abbr': 'saint-peters',
                 'away_score': 40,
                 'away_rank': None,
                 'home_name': 'La Salle',
                 'home_abbr': 'la-salle',
                 'home_score': 61,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-15-longwood',
                 'away_name': 'Stephen F. Austin',
                 'away_abbr': 'stephen-f-austin',
                 'away_score': 74,
                 'away_rank': None,
                 'home_name': 'Longwood',
                 'home_abbr': 'longwood',
                 'home_score': 61,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-16-arkansas-little-rock',
                 'away_name': 'Ouachita',
                 'away_abbr': 'Ouachita',
                 'away_score': 81,
                 'away_rank': None,
                 'home_name': 'Little Rock',
                 'home_abbr': 'arkansas-little-rock',
                 'home_score': 79,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-16-california-santa-barbara',
                 'away_name': 'North Dakota State',
                 'away_abbr': 'north-dakota-state',
                 'away_score': 66,
                 'away_rank': None,
                 'home_name': 'UCSB',
                 'home_abbr': 'california-santa-barbara',
                 'home_score': 85,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-16-depaul',
                 'away_name': 'Notre Dame',
                 'away_abbr': 'notre-dame',
                 'away_score': 72,
                 'away_rank': 14,
                 'home_name': 'DePaul',
                 'home_abbr': 'depaul',
                 'home_score': 58,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': True},
                {'boxscore': '2017-11-11-17-duquesne',
                 'away_name': 'St. Francis (NY)',
                 'away_abbr': 'st-francis-ny',
                 'away_score': 70,
                 'away_rank': None,
                 'home_name': 'Duquesne',
                 'home_abbr': 'duquesne',
                 'home_score': 80,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-18-njit',
                 'away_name': 'Wagner',
                 'away_abbr': 'wagner',
                 'away_score': 60,
                 'away_rank': None,
                 'home_name': 'NJIT',
                 'home_abbr': 'njit',
                 'home_score': 49,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-akron',
                 'away_name': 'Cleveland State',
                 'away_abbr': 'cleveland-state',
                 'away_score': 57,
                 'away_rank': None,
                 'home_name': 'Akron',
                 'home_abbr': 'akron',
                 'home_score': 67,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-duke',
                 'away_name': 'Utah Valley',
                 'away_abbr': 'utah-valley',
                 'away_score': 69,
                 'away_rank': None,
                 'home_name': 'Duke',
                 'home_abbr': 'duke',
                 'home_score': 99,
                 'home_rank': 1,
                 'non_di': False,
                 'top_25': True},
                {'boxscore': '2017-11-11-19-elon',
                 'away_name': 'Peace',
                 'away_abbr': 'Peace',
                 'away_score': 53,
                 'away_rank': None,
                 'home_name': 'Elon',
                 'home_abbr': 'elon',
                 'home_score': 96,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-marist',
                 'away_name': 'Lehigh',
                 'away_abbr': 'lehigh',
                 'away_score': 84,
                 'away_rank': None,
                 'home_name': 'Marist',
                 'home_abbr': 'marist',
                 'home_score': 76,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-michigan',
                 'away_name': 'North Florida',
                 'away_abbr': 'north-florida',
                 'away_score': 66,
                 'away_rank': None,
                 'home_name': 'Michigan',
                 'home_abbr': 'michigan',
                 'home_score': 86,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-north-carolina-wilmington',
                 'away_name': 'North Carolina Wesleyan',
                 'away_abbr': 'North Carolina Wesleyan',
                 'away_score': 81,
                 'away_rank': None,
                 'home_name': 'North Carolina-Wilmington',
                 'home_abbr': 'north-carolina-wilmington',
                 'home_score': 105,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-presbyterian',
                 'away_name': 'Johnson University',
                 'away_abbr': 'Johnson University',
                 'away_score': 87,
                 'away_rank': None,
                 'home_name': 'Presbyterian',
                 'home_abbr': 'presbyterian',
                 'home_score': 107,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-sam-houston-state',
                 'away_name': 'Texas-Tyler',
                 'away_abbr': 'Texas-Tyler',
                 'away_score': 51,
                 'away_rank': None,
                 'home_name': 'Sam Houston State',
                 'home_abbr': 'sam-houston-state',
                 'home_score': 91,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-south-dakota',
                 'away_name': 'Mayville State',
                 'away_abbr': 'Mayville State',
                 'away_score': 59,
                 'away_rank': None,
                 'home_name': 'South Dakota',
                 'home_abbr': 'south-dakota',
                 'home_score': 87,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-19-toledo',
                 'away_name': "St. Joseph's",
                 'away_abbr': 'saint-josephs',
                 'away_score': 87,
                 'away_rank': None,
                 'home_name': 'Toledo',
                 'home_abbr': 'toledo',
                 'home_score': 98,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-20-nebraska',
                 'away_name': 'Eastern Illinois',
                 'away_abbr': 'eastern-illinois',
                 'away_score': 68,
                 'away_rank': None,
                 'home_name': 'Nebraska',
                 'home_abbr': 'nebraska',
                 'home_score': 72,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-20-saint-marys-ca',
                 'away_name': 'Saint Francis (PA)',
                 'away_abbr': 'saint-francis-pa',
                 'away_score': 68,
                 'away_rank': None,
                 'home_name': "Saint Mary's (CA)",
                 'home_abbr': 'saint-marys-ca',
                 'home_score': 85,
                 'home_rank': 22,
                 'non_di': False,
                 'top_25': True},
                {'boxscore': '2017-11-11-20-texas-arlington',
                 'away_name': 'Loyola Marymount',
                 'away_abbr': 'loyola-marymount',
                 'away_score': 80,
                 'away_rank': None,
                 'home_name': 'Texas-Arlington',
                 'home_abbr': 'texas-arlington',
                 'home_score': 85,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-20-western-illinois',
                 'away_name': "Saint Mary's (MN)",
                 'away_abbr': "Saint Mary's (MN)",
                 'away_score': 68,
                 'away_rank': None,
                 'home_name': 'Western Illinois',
                 'home_abbr': 'western-illinois',
                 'home_score': 109,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-21-brigham-young',
                 'away_name': 'Mississippi Valley State',
                 'away_abbr': 'mississippi-valley-state',
                 'away_score': 61,
                 'away_rank': None,
                 'home_name': 'BYU',
                 'home_abbr': 'brigham-young',
                 'home_score': 91,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-21-kent-state',
                 'away_name': 'Youngstown State',
                 'away_abbr': 'youngstown-state',
                 'away_score': 78,
                 'away_rank': None,
                 'home_name': 'Kent State',
                 'home_abbr': 'kent-state',
                 'home_score': 111,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-21-new-mexico',
                 'away_name': 'Northern New Mexico',
                 'away_abbr': 'Northern New Mexico',
                 'away_score': 76,
                 'away_rank': None,
                 'home_name': 'New Mexico',
                 'home_abbr': 'new-mexico',
                 'home_score': 147,
                 'home_rank': None,
                 'non_di': True,
                 'top_25': False},
                {'boxscore': '2017-11-11-22-nevada-las-vegas',
                 'away_name': 'Florida A&M',
                 'away_abbr': 'florida-am',
                 'away_score': 66,
                 'away_rank': None,
                 'home_name': 'UNLV',
                 'home_abbr': 'nevada-las-vegas',
                 'home_score': 108,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False},
                {'boxscore': '2017-11-11-22-portland',
                 'away_name': 'Portland State',
                 'away_abbr': 'portland-state',
                 'away_score': 80,
                 'away_rank': None,
                 'home_name': 'Portland',
                 'home_abbr': 'portland',
                 'home_score': 75,
                 'home_rank': None,
                 'non_di': False,
                 'top_25': False}
            ]
        }

        result = Boxscores(datetime(2017, 11, 11)).games

        assert result == expected
